Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -25,6 +25,15 @@ steps:
 - task: SSH@0
   inputs:
     sshEndpoint: 'DevServer'
-    runOptions: 'script'
-    scriptPath: '/deploy/unittest.sh'
+    runOptions: 'commands'
+    commands: |
+      #Unit Testing
+      echo "unit testing started"
+      if grep 'Fatel' /deploy//index.php; then
+      echo "Test is failed in following number of line"
+      sed -n '/Fatel/=' /deploy/index.html
+      exit 1
+      fi
+      echo "Test is Successful"
+    failOnStdErr: false
     readyTimeout: '20000'
