Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -22,16 +22,17 @@ steps:
     contents: '**'
     targetFolder: '/deploy'
     readyTimeout: '20000'
-- task: Maven@4
+- task: SSH@0
   inputs:
-    azureSubscription: 'Azure subscription 1(98aa80c2-2099-40d5-9ab7-a3dd3db1ba39)'
-    mavenPomFile: 'pom.xml'
-    publishJUnitResults: true
-    testResultsFiles: '**/surefire-reports/TEST-*.xml'
-    javaHomeOption: 'JDKVersion'
-    mavenVersionOption: 'Default'
-    mavenAuthenticateFeed: false
-    effectivePomSkip: false
-    sonarQubeRunAnalysis: false
-    checkStyleRunAnalysis: true
-    findBugsRunAnalysis: true
+    sshEndpoint: 'DevServer'
+    runOptions: 'commands'
+    commands: |
+      #Unit Testing
+      echo "unit testing started"
+      if grep 'Fatel' /build/$JOB_NAME-$BUILD_NUMBER/index.html; then
+       echo "Test is failed in following number of line"
+       sed -n '/Fatel/=' /build/$JOB_NAME-$BUILD_NUMBER/index.html
+       exit 1
+      fi
+      echo "Test is Successful"
+    readyTimeout: '20000'
